# -*- coding: utf-8 -*-
"""lda_topic_modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OeHI7qdYUUmNkJlvailfkNi1_itHiD0L
"""

## 🔍 LDA 기반 토픽 모델링 (lda_topic_modeling.py)

# Gensim의 `LdaModel`을 활용하여 전처리된 관광지 리뷰 데이터(`processed_data`)에서 주요 주제를 추출합니다.
# 불용어 제거 및 토큰화를 거친 데이터에서 `Dictionary`와 `Corpus`를 생성한 후, LDA 학습을 수행합니다.
# `filter_extremes(no_below=2, no_above=0.5)`를 통해 너무 드물거나 흔한 단어를 제거하여 주제의 품질을 향상시켰습니다.

```python
from gensim.models.ldamodel import LdaModel
from gensim import corpora
from gensim.models.callbacks import CoherenceMetric, PerplexityMetric

# 사전(dictionary) 및 코퍼스 생성
dictionary = corpora.Dictionary(processed_data)
dictionary.filter_extremes(no_below=2, no_above=0.5)
corpus = [dictionary.doc2bow(text) for text in processed_data]

# 이후 LDA 학습 가능:
# lda_model = LdaModel(corpus=corpus, num_topics=5, id2word=dictionary, passes=10, callbacks=[...])